
:labname: Pipelines

{labname} Lab

= はじめに
include::_attributes.adoc[]

Red Hat OpenShift Pipelinesは、Kubernetesリソースに基づくクラウドネイティブの継続的インテグレーションおよび継続的デリバリー（CI / CD）ソリューションです。

Tektonビルディングブロックを使用して、基盤となる実装の詳細を抽象化することにより、複数のプラットフォームにわたる展開を自動化します。

Tektonは、Kubernetesディストリビューション間で移植可能なCI / CDパイプラインを定義するためのいくつかの標準カスタムリソース定義（CRD）を導入しています。 

OpenShift Pipelines Operatorはすでにデプロイされているため、すぐに開始できます。

このラボでは、

. 新しいプロジェクトを作成し、1つのパイプラインで "helloworld" という簡単なタスクをデプロイします
. 2層の Golang のアプリケーションを構築およびデプロイするために必要なさまざまなリソースをデプロイします

.ゴール
* 簡単なパイプラインのデプロイ
* ビルドパイプラインのデプロイ

[#prerequisite]
== 準備
=== OpenShift Pipelines のインストール 
あとで書く。

=== tkn コマンドなどのインストール （オプション）
今回のLabでは tkn コマンドは使いませんが、利用イメージをご紹介します。

. tkn コマンドのインストール
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
mkdir tkn
cd tkn
wget https://mirror.openshift.com/pub/openshift-v4/clients/pipeline/1.9.0/tkn-linux-amd64.tar.gz
tar xvzf tkn-linux-amd64.tar.gz
export PATH=$PATH:$HOME/tkn
----

. Taskの一覧を表示
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
tkn task list
----
+
[NOTE]
====
Taskが登録されていないことがわかります。
====

. ClusterTaskの一覧を表示
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
tkn clustertask list
----
+
[NOTE]
====
ClusterTaskは、Tekton Catalogの一部がデフォルトで登録されていることがわかります。
====

[#sample]
== 簡単なパイプラインのデプロイ

`trivial-pipeline` プロジェクトの作成

. OpenShift web コンソールで *管理者* パースペクティブを選択
. 左のナビゲーションバーで *プロジェクト* を選択し、右にある *プロジェクトの作成* をクリック `trivial-pipeline` を *名前* に入力し、作成します。
. 以下の YAML をインポートして、次の方法で新しいタスクを作成します
.. 左のナビゲーションバーで *パイプライン* さらに *タスク* をクリック
.. *作成* をクリックし、ドロップダウンから *タスク* を選択
.. 表示されたデフォルトの YAML 定義を次のように置き換えます
+
[.console-input]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
  namespace: trivial-pipeline
spec:
  steps:
    - name: say-hello
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash
      args: ['-c', 'echo Hello World']
----
+
. [blue-background white]#作成# ボタンをクリック

=== TaskRun を使ってサンプルタスク "hello" を実行

タスクを実行するには、TaskRunオブジェクトを作成する必要があります。
コマンドラインの `tkn` ユーティリティを使用するか、次の yaml をインポートできます。

. 左のナビゲーションバーでもう一度 *Tasks* をクリックします
. [blue-background white]#作成# ボタンをクリックしドロップダウンメニューから *タスクの実行* を選択します
. デフォルトの YAML を以下のように変更し、作成をクリックします
+
[.console-input]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  namespace: trivial-pipeline
  generateName: hello-run-
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/task: hello
spec:
  resources: {}
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: hello
----
+
. *ログ* タブをクリックし実行したタスクを確認します。"Hello World" が表示されていると思います。

[#createtask]
== Golang の 2 Tier アプリケーションのデプロイ

=== リソースを定義するタスクを作成する

次に、いくつかのTask、ClusterTasks、およびカスタムタスクを使用してアプリケーションをビルドおよびデプロイしましょう。

まず、この作業用の名前空間/プロジェクトを作成しましょう。

. *Project:* のドロップダウンボックスから、*Create Project* を選び、*Name:* に `pipelines-vote` を入力し新しいプロジェクトを作成します
. ナビゲーションバーから *Pipelines* -> *Tasks* を選択、[blue-background white]#Create# を選び、 *Task* を選択します
. デフォルトの YAML を以下のように変更し、作成をクリックします
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
# task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifests
  namespace: pipelines-vote
spec:
  workspaces:
  # ----- <a> ----- 
  - name: source 
  # ----- <b> ----- 
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
  # ----- <c> ----- 
  steps: 
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      # ----- <d> ----- 
      args:
        - |-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          oc apply -f $(inputs.params.manifest_dir)
          echo -----------------------------------
----
+
*備考：*
+
* `<a>` `workspaces` とはパラメータやタスクの出力が格納されるPVCを示していている。これに "source" と名前をつけます。
* `<b>` このタスクが受け付ける1つのパラメータです。ここでは、アプリケーションをデプロイするためのyamlマニフェストが存在するディレクトリを示します。
* `<c>` このタスクの1つのステップです。このタスクは、パラメータで定義された `manifest_dir` 内のすべてのファイルに対して `oc apply -f` を実行することで、実際に OpenShift　のオブジェクトを作成します。
* `<d>` ステップの中でパラメータが `$(inputs.params.)` という構文で参照されていることに注意してください。
+
. [blue-background white]#Create#　をクリックします。

[NOTE]
====
パラメータを使用するタスクに送信される前に、パラメータはどこで定義されるのでしょうか？
*TaskRuns* の中です。上記のtrivial-pipelineで行ったように、個々のTaskRunを作成することもできますし、以下で説明するように、*PipelineRun* にこれらの値を与えることもできます。
====

=== Deploymentリソースで展開されたイメージの名前を更新するタスクを作成する

パイプラインでは、アプリケーションを新たにビルドするたびに新しいコンテナイメージを構築しているため、新しいコンテナイメージには異なるタグやハッシュ値が設定されます。

Podの再デプロイ時に適切なコンテナイメージが使用されていることを確認するために、パイプラインにタスクが必要です。

. もう一度 [blue-background white]#Create# をクリックし、 *Task* リソースを選択します.
. デフォルトの YAML を以下のように変更し、作成をクリックします
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment
  namespace: pipelines-vote
spec:
  workspaces:
  # ----- <a> ----- 
  - name: source 
  params:
  # ----- <a> ----- 
  - description: The name of the deployment patch the image 
    name: deployment
    type: string
  # ----- <a> ----- 
  - description: Location of image to be patched with
    name: IMAGE
    type: string
  steps:
  - args:
    - |-
      oc patch deployment $(inputs.params.deployment) --patch='{"spec":{"template":{"spec":{
        "containers":[{
          "name": "$(inputs.params.deployment)",
          "image":"$(inputs.params.IMAGE)"
        }]
      }}}}'
    command:
    - /bin/bash
    - -c
    # ----- <b> ----- 
    image: quay.io/openshift/origin-cli:latest 
    name: patch
    resources: {}
----
+
*備考：*
+
* `<a>` これらは *Task* リソースが、*TaskRun* リソースから受け取ろうとしているこパラメータです。
* `<b>` この *Task* は、OpenShiftのコマンドラインツールである `oc.` 専用のコンテナを使用します。
+
. [blue-background white]#Create# をクリックします。

[#createpvc]
=== Workspaceのデータを保存する、Persistent Volume Claim リソースの作成

* *Task* のパラメータと結果の出力は、Tektonによって専用の永続的なボリューム・クレームに自動的に保存されます。
* これら *Workspaces* は、*PipelineRun* によってタスクに関連付けられており、任意の数のワークスペースを持つことができます。
* さらに、*Workspaces* は1つまたは複数のタスクにまたがることができ、*Task* がお互いのデータにアクセスできる共有領域を証明することができます。これらは通常のPVCです。


. OpenShiftのWebコンソールの右上の "+" ボタンををクリックし、以下のYAMLを貼り付けて、*Workspace* をサポートするPVC を作成します。
+
[NOTE]
====
定義を適用してPVCリソースを作成するために、右上の "+" ボタンをよく使うことにしています。
同様に、*Storage* -> *PersistentVolumeClaims* -> [blue-background white]#Create# を使用することもできます。
====
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
----
[#createpipeline]
=== 自前のアプリのビルド・デプロイ パイプラインを作成する

今作成中のパイプラインは３つの大きいセクションと、４つの *Task* で構成されています。
セクションは以下です。

Workspaces::
*Workspace* を使用する *Task* リソースにコンテキストを提供するために定義されています
Params::
パイプラインが *PipelineRun* から期待され、*Task*　リソースで利用できる入力が定義されています
Tasks::
実行されるタスクが定義される *Tasks* の配列、*Workspace* は *Tasks* が利用可能なように作成され、渡されるパラメータを定義している
+
[WARNING]
====
パイプラインの定義にあるようなタスクの順序は適用されません。いくつかのステップには `runAfter` という値があり、現在のステップが後に実行すべき特定のタスクを示しています。Tektonのデフォルトでは、すべてのステップを並行して実行するため、この値が必要になります。
これは、他の継続的統合システムとの重要な差別化要因として覚えておいてください。
====

. ナビゲーションバーより *Pipeline* を選択し、[blue-background white]#Create# -> *Pipeline* で *Pipeline* リソースを作成します
. *&#128280; YAML view* のラジオボタンをクリックし、定義を貼り付けるためのテキストエリアを表示します
. デフォルトの YAML を以下のように変更し、作成をクリックします
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  # ----- <a> ----- 
  workspaces: 
  - name: shared-workspace
  # ----- <b> ----- 
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: IMAGE
    type: string
    description: image to be build from the code
  # ----- <c> ----- 
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    # ----- <d> ----- 
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    #  ----- <d> ----- 
    - name: source
      workspace: shared-workspace
    #  ----- <e> ----- 
    runAfter:
    - fetch-repository
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - build-image
  - name: update-deployment
    taskRef:
      name: update-deployment
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: deployment
      value: $(params.deployment-name)
    - name: IMAGE
      value: $(params.IMAGE)
    runAfter:
    - apply-manifests
----
+
*備考：*
+
* `<a>` ここのタスクと共有されるPVCを定義します。  
* `<b>` パイプラインが *PipelineRun* リソースから期待するパラメータが定義されています  
* `<c>` *Task* リソースの配列。このリストの表示順に実行されるわけではありません  
* `<d>` *Workplace* の詳細: これらの#4の設定はいずれも、ワークスペースのファイルシステム内の異なるサブディレクトリ ( `output` and `source` ) を示しています。Tektonはこれらを自動的に整理し、必要に応じて、先ほど見たように、 `$(input.)` を介して、*お互いのデータにアクセスすることができます*。  
* `<e>` `runAfter:` は *Task* の中で設定され、このパイプライン内のタスクの実行順序を定義します。  

. [blue-background white]#Create# をクリックします。

[#runpipeline]
=== VotingアプリのバックエンドAPI用のパイプラインを実行します

さて、お楽しみの時間です！Votingアプリのバックエンド部分のパイプラインを実行してみましょう。

ナビゲーションバーより *Pipeline* を選択し、[blue-background white]#Create# -> *PipelineRun* でリソースを作成します
. デフォルトの YAML を以下のように変更し、作成をクリックします

[.console-input]
[source,bash,subs="attributes+,+macros"]
----
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: build-and-deploy
  generateName: build-and-deploy-run-backendapp-
  namespace: pipelines-vote
spec:
  # ----- <a> ----- 
  params: 
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/pipelines-vote/vote-api
  - name: deployment-name
    value: pipelines-vote-api
  - name: git-url
    value: https://github.com/openshift/pipelines-vote-api.git
  # ----- <b> ----- 
  pipelineRef:
    name: build-and-deploy
  serviceAccountName: pipeline
  timeout: 1h0m0s
  # ----- <c> ----- 
  workspaces: 
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc
----
+
*備考：*

* `<a>` この *PipelineRun* が作成する *TaskRuns* によって、*Task* リソースに渡す実際の文字列の値です。
* `<b>` 前のセクションで作成したPipelineへの参照です。
* `<c>` 最後に *Workspace* の定義です。ここで、PVC と *Workspace* がひもづけられています。

[blue-background white]#Create# をクリックし、パイプラインの実行を見てみましょう！

これで、アプリケーションの一部分がデプロイされました。
早速、アプリケーションのフロントエンド部分を見てみましょう。

=== VotingアプリのフロントエンドAPI用のパイプラインを実行します
それでは、アプリケーションを全てデプロイしましょう！

. バックエンドのときと同様に、以下の *PipelineRun* 定義を使用してビルドを実行し、アプリケーションをデプロイします。
+
[.console-input]
[source,bash,subs="attributes+,+macros"]
----
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-run-frontendapp-
  labels:
    tekton.dev/pipeline: build-and-deploy
  namespace: pipelines-vote
spec:
  params:
  - name: IMAGE
    #<a>
    value: image-registry.openshift-image-registry.svc:5000/pipelines-vote/vote-ui
  - name: deployment-name
    value: pipelines-vote-ui
  - name: git-url
    #<b>
    value: https://github.com/openshift/pipelines-vote-ui.git
  pipelineRef:
    name: build-and-deploy
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc
----
+
*備考：*

* `<a>` ビルドが書き込まれるイメージ名と、*Pod* がデプロイされるイメージ名が異なることに注意してください。
* `<b>` アプリケーションのフロントエンド用に異なるリポジトリを使用しています。この場合、monorepoはどのように使用されたのでしょうか？

[blue-background white]#Create# をクリックし、パイプラインの実行を見てみましょう！

=== アプリケーションへアクセスする

ビルドが完了すると、Vote アプリケーション UIのURLを取得することができます。

. 左のナビゲーションバー *Networking* をクリックすると、UIへのルートが記載されています。
. クリックして、投票してください。

== まとめ

Pipelines は複雑ですが、Tasks は非常に強力で、TaskRuns で簡単にテストできます。パイプラインにコンテナイメージのスキャンやテストを追加することで、バグやセキュリティの問題を早期に発見することができます。
